<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

class Haayal_AI_Slug_Posts {
    private $slug_meta_key = '_slug_source';

    
    public function __construct() {
        add_filter( 'wp_insert_post_data', [ $this, 'generate_slug_on_title_entry' ], 10, 2 );
        add_action( 'save_post', [ $this, 'track_slug_edits' ], 9, 2 );
        add_action( 'save_post', [ $this, 'sync_slug_on_save' ], 10 );
        add_filter( 'get_sample_permalink_html', [ $this, 'add_slug_indicator' ], 10, 5 );
        add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_classic_editor_assets' ] );
        add_action( 'enqueue_block_editor_assets', [ $this, 'enqueue_gutenberg_assets' ] );
        add_action( 'rest_api_init', [ $this, 'register_translate_endpoint' ] );
    }

    /**
     * Generates and stores a slug after the title is entered.
     *
     * @param array $data An array of slashed post data.
     * @param array $postarr The raw post array.
     * @return array Modified post data with the AI-generated slug.
     */
    public function generate_slug_on_title_entry( $data, $postarr ) {

        // Skip autosave, revisions, or auto-drafts
        if ( wp_is_post_autosave( $postarr['ID'] ) || wp_is_post_revision( $postarr['ID'] ) || $data['post_status'] === 'auto-draft' ) {
            return $data;
        }

        // Check if the post type is supported
        $settings = Haayal_AI_Slug_Settings::get_settings();
        if ( ! in_array( $data['post_type'], $settings['enabled_post_types'], true ) ) {
            return $data;
        }

        // Skip if the slug is already manually set
        if ( ! empty( $postarr['post_name'] ) ) {
            return $data;
        }

        $existing_slug = get_post_meta( $postarr['ID'], '_generated_slug', true );
        $source = get_post_meta( $postarr['ID'], '_slug_source', true );

        if ( $existing_slug && $source === 'ai' ) {
            // Already generated by AI - Use it.
            $data['post_name'] = $existing_slug;
            return $data;
        }

        // For existing posts that already have a slug in the DB, don't overwrite.
        // Page builders (e.g. Bricks) do background saves that omit post_name; without
        // this guard the plugin would make an API call and replace the existing slug.
        if ( ! empty( $postarr['ID'] ) && get_post_field( 'post_name', $postarr['ID'] ) ) {
            return $data;
        }

        $title = $data['post_title'];

        // Generate a new slug using the AI
        $api_key = $settings['api_key'];

        Haayal_AI_Slug_Log::set_context( [ 'object_id' => $postarr['ID'], 'object_type' => 'post' ] );

        if ( empty( $title ) ) {
            Haayal_AI_Slug_Log::add_entry(
                __( 'Title is empty or missing.', 'haayal-ai-slug-translator' ),
                __( 'Unknown Title', 'haayal-ai-slug-translator' )
            );
            return $data;
        }
        
        $slug = Haayal_AI_Slug_Helpers::translate_and_track( $title, $api_key, $settings['max_tokens'] ?? 20 );

        if ( $slug ) {
            update_post_meta( $postarr['ID'], '_generated_slug', $slug );
            update_post_meta( $postarr['ID'], $this->slug_meta_key, 'ai' );
            $data['post_name'] = $slug;
        }

        Haayal_AI_Slug_Log::set_context();
        return $data;
    }

    /**
     * Ensures the slug matches the generated slug on save.
     *
     * @param int $post_id The ID of the post being saved.
     */
    public function sync_slug_on_save( $post_id ) {
        // Skip autosave, revisions, or auto-drafts
        if ( wp_is_post_autosave( $post_id ) || wp_is_post_revision( $post_id ) ) {
            return;
        }

        // Load the post object
        $post = get_post( $post_id );

        // Validate the post object
        if ( ! $post || $post->post_status === 'auto-draft' ) {
            return;
        }

        // Check if the post type is supported
        $settings = Haayal_AI_Slug_Settings::get_settings();
        if ( ! in_array( $post->post_type, $settings['enabled_post_types'], true ) ) {
            return;
        }

        // Retrieve the generated slug
        $generated_slug = get_post_meta( $post_id, '_generated_slug', true );
        $slug_source    = get_post_meta( $post_id, '_slug_source', true );

        // Only restore the AI slug if the user hasn't manually edited it.
        // track_slug_edits (priority 9) already ran by this point, so _slug_source
        // reflects the current state before we act on it.
        // Use a direct DB write instead of wp_update_post() to avoid triggering
        // a second save_post cycle, which causes page builders (e.g. Bricks) to
        // overwrite their freshly saved data with an empty second-pass request.
        if ( $generated_slug && $slug_source === 'ai' && $post->post_name !== $generated_slug ) {
            global $wpdb;
            $wpdb->update(
                $wpdb->posts,
                [ 'post_name' => $generated_slug ],
                [ 'ID'        => $post_id ],
                [ '%s' ],
                [ '%d' ]
            );
            clean_post_cache( $post_id );
        }
    }


    /**
     * Tracks slug edits and updates the meta key accordingly.
     *
     * @param int $post_id The ID of the post being saved.
     * @param WP_Post $post The post object.
     */
    public function track_slug_edits( $post_id, $post ) {
        // Skip autosave, revisions, or auto-drafts
        if ( wp_is_post_autosave( $post_id ) || wp_is_post_revision( $post_id ) ) {
            return;
        }

        // Retrieve the previous slug from the meta key
        $previous_slug = get_post_meta( $post_id, '_generated_slug', true );

        // If the slug has been edited by the user, update the meta key
        if ( $previous_slug && $post->post_name !== $previous_slug ) {
            update_post_meta( $post_id, '_slug_source', 'user-edited' );
        }
    }


    /**
     * Adds a custom indicator to the permalink HTML based on the slug source.
     *
     * @param string  $permalink_html The permalink HTML.
     * @param int     $post_id The post ID.
     * @param string  $new_title The new title.
     * @param string  $new_slug The new slug.
     * @param WP_Post $post The post object.
     * @return string The modified permalink HTML with the indicator.
     */
    public function add_slug_indicator( $permalink_html, $post_id, $new_title, $new_slug, $post ) {
        // Retrieve the slug source meta key
        $slug_source = get_post_meta( $post_id, '_slug_source', true );

        $ai_icon   = '<svg aria-hidden="true" class="haayal-badge-icon" width="13" height="13" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2m-2 15-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8z"/></svg>';
        $edit_icon = '<svg aria-hidden="true" class="haayal-badge-icon" width="13" height="13" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75zM20.71 7.04a1 1 0 0 0 0-1.41l-2.34-2.34a1 1 0 0 0-1.41 0l-1.83 1.83 3.75 3.75z"/></svg>';

        // When the user edits the slug via the AJAX call in the classic editor, $new_slug holds
        // the typed value before the post is saved. Treat it as user-edited immediately.
        $effective_source = $slug_source;
        if ( $slug_source === 'ai' && ! empty( $new_slug ) && $new_slug !== $post->post_name ) {
            $effective_source = 'user-edited';
        }

        if ( $effective_source === 'ai' ) {
            $indicator  = '<span class="ai-slug-indicator haayal-pill haayal-pill--ai">';
            $indicator .= $ai_icon . esc_html__( 'Slug generated by AI', 'haayal-ai-slug-translator' );
            $indicator .= '</span>';
        } elseif ( $effective_source === 'user-edited' ) {
            $indicator  = '<span class="ai-slug-indicator haayal-pill haayal-pill--edited">';
            $indicator .= $edit_icon . esc_html__( 'Slug manually edited', 'haayal-ai-slug-translator' );
            $indicator .= '</span>';
        } else {
            $indicator = '';
        }

        $settings = Haayal_AI_Slug_Settings::get_settings();

        // Add regenerate button for unpublished posts of enabled post types only,
        // and only when the title or slug contains non-Latin characters worth translating.
        $regenerate = '';
        if (
            in_array( $post->post_status, [ 'auto-draft', 'draft', 'pending' ], true ) &&
            in_array( $post->post_type, $settings['enabled_post_types'], true ) &&
            (
                Haayal_AI_Slug_Helpers::has_non_latin_chars( $new_title ) ||
                Haayal_AI_Slug_Helpers::has_non_latin_chars( $post->post_name )
            )
        ) {
            $regen_icon  = '<svg aria-hidden="true" class="haayal-regen-icon" width="14" height="14" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><path d="M50 85.625c-9.822 0-18.728-3.996-25.179-10.447l9.434-9.433c1.428-1.428.417-3.87-1.602-3.87H6.573A4.073 4.073 0 0 0 2.5 65.948v26.08c0 2.02 2.442 3.03 3.87 1.602l10.058-10.058C25.03 92.172 36.904 97.5 50 97.5c24.609 0 44.907-18.812 47.27-42.81.248-2.52-1.778-4.69-4.31-4.69h-3.25c-2.219 0-4.055 1.682-4.296 3.888C83.471 71.709 68.33 85.625 50 85.625M50 2.5C25.39 2.5 5.093 21.311 2.73 45.31 2.482 47.83 4.508 50 7.04 50h3.25c2.219 0 4.055-1.682 4.296-3.888C16.529 28.291 31.67 14.375 50 14.375c9.822 0 18.728 3.996 25.179 10.446l-9.434 9.434c-1.428 1.428-.417 3.87 1.602 3.87h26.08a4.073 4.073 0 0 0 4.073-4.073V7.972c0-2.02-2.442-3.03-3.87-1.602L83.572 16.428C74.97 7.828 63.096 2.5 50 2.5"/></svg>';
            $regen_label  = esc_html__( 'Regenerate slug', 'haayal-ai-slug-translator' );
            $translating  = esc_attr__( 'Translating…', 'haayal-ai-slug-translator' );
            $already_best = esc_attr__( 'I tried, but this is already the best option', 'haayal-ai-slug-translator' );

            $regenerate  = '<span class="haayal-regen-wrap">';
            $regenerate .= '<button type="button" id="haayal-regen-btn" class="haayal-pill haayal-pill-regen" data-translating="' . $translating . '" data-already-best="' . $already_best . '">';
            $regenerate .= $regen_icon . $regen_label;
            $regenerate .= '</button></span>';
            $regenerate .= $this->get_classic_regenerate_script( $post_id );
        }

        $bulk_link = '';
        if ( empty( $slug_source ) && current_user_can( 'manage_options' ) && in_array( $post->post_type, $settings['enabled_post_types'], true ) && Haayal_AI_Slug_Helpers::has_non_latin_chars( $post->post_name ) ) {
            $bulk_url       = admin_url( 'options-general.php?page=ai-slug-translator&tab=bulk' );
            $bulk_label     = esc_html__( 'Bulk translate slugs', 'haayal-ai-slug-translator' );
            $external_icon  = '<svg aria-hidden="true" class="haayal-badge-icon" width="12" height="12" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M19 19H5V5h7V3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7h-2zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3z"/></svg>';
            $bulk_link  = '<a href="' . esc_url( $bulk_url ) . '" target="_blank" rel="noopener noreferrer" class="haayal-pill haayal-pill--bulk haayal-classic-bulk-link">';
            $bulk_link .= $bulk_label . ' ' . $external_icon . '</a>';
        }

        return $permalink_html . $indicator . $regenerate . $bulk_link;
    }

    /**
     * Returns inline JS for the classic editor regenerate button.
     *
     * WHY INLINE: This method is called from the `get_sample_permalink_html` filter, which
     * returns a string that WordPress concatenates directly into permalink HTML — there is no
     * enqueue hook available at this point in the request lifecycle. The required data
     * (REST URL, WP REST nonce, post ID, AI badge HTML) is post-specific and cannot be
     * pre-localized via wp_localize_script() without knowing the post context at enqueue time.
     * Extracting this to a static file would require a separate AJAX request just to fetch the
     * nonce, which is worse than a small inline script. Keep this inline intentionally.
     *
     * @param int $post_id The post ID.
     * @return string Script tag.
     */
    private function get_classic_regenerate_script( $post_id ) {
        $rest_url      = esc_url_raw( rest_url( 'haayal-ai-slug/v1/translate' ) );
        $nonce         = wp_create_nonce( 'wp_rest' );
        $post_id       = (int) $post_id;
        $ai_icon_svg   = '<svg aria-hidden="true" class="haayal-badge-icon" width="13" height="13" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2m-2 15-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8z"/></svg>';
        $ai_badge_html = wp_json_encode( $ai_icon_svg . esc_html__( 'Slug generated by AI', 'haayal-ai-slug-translator' ) );

        ob_start();
        ?>
        <script>
        (function(){
            var btn = document.getElementById('haayal-regen-btn');
            if (!btn) return;

            var origHTML        = btn.innerHTML;
            var translatingText = btn.getAttribute('data-translating');
            var alreadyBest     = btn.getAttribute('data-already-best');

            function showTooltip(message) {
                var tip = document.createElement('div');
                tip.className = 'haayal-slug-tooltip';
                tip.textContent = message;
                document.body.appendChild(tip);

                var rect = btn.getBoundingClientRect();
                var top  = rect.top - tip.offsetHeight - 6;
                if (top < 4) { top = rect.bottom + 6; }
                var left = rect.left + rect.width / 2 - tip.offsetWidth / 2;
                if (left < 4) { left = 4; }

                tip.style.top  = top + 'px';
                tip.style.left = left + 'px';

                setTimeout(function() {
                    tip.style.opacity = '0';
                    setTimeout(function() { if (tip.parentNode) { tip.parentNode.removeChild(tip); } }, 300);
                }, 3000);
            }

            btn.addEventListener('click', function(e) {
                e.preventDefault();
                if (btn.disabled) return;

                var titleEl = document.getElementById('title');
                if (!titleEl || !titleEl.value.trim()) return;

                var oldSlug = (document.getElementById('editable-post-name') || {}).textContent || '';

                btn.disabled = true;
                var icon = btn.querySelector('svg');
                if (icon) { icon.classList.add('haayal-icon-spin'); }
                btn.childNodes.forEach(function(n){ if (n.nodeType === 3) n.textContent = translatingText; });

                fetch('<?php echo esc_url( $rest_url ); ?>', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-WP-Nonce': '<?php echo esc_attr( $nonce ); ?>'
                    },
                    body: JSON.stringify({ title: titleEl.value.trim(), post_id: <?php echo absint( $post_id ); ?> })
                })
                .then(function(r){ return r.json(); })
                .then(function(data){
                    btn.disabled = false;
                    btn.innerHTML = origHTML;

                    if (data.slug) {
                        if (data.slug.trim() === oldSlug.trim()) {
                            showTooltip(alreadyBest);
                        } else {
                            // Update the hidden form input so the new slug is submitted on save.
                            var postNameInput = document.getElementById('post_name');
                            if (postNameInput) { postNameInput.value = data.slug; }
                            // Update the editable slug field.
                            var slugInput = document.getElementById('new-post-slug');
                            if (slugInput) { slugInput.value = data.slug; }
                            // Update the visible permalink display.
                            var editable = document.getElementById('editable-post-name');
                            if (editable) { editable.textContent = data.slug; }
                            var fullEl = document.getElementById('editable-post-name-full');
                            if (fullEl) { fullEl.textContent = data.slug; }
                            // Swap the badge back to "AI".
                            var indicator = document.querySelector('.ai-slug-indicator');
                            if (indicator) {
                                indicator.classList.remove('haayal-pill--edited');
                                indicator.classList.add('haayal-pill--ai');
                                indicator.innerHTML = <?php echo $ai_badge_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Value is wp_json_encode() of sanitized SVG + esc_html string. ?>;
                            }
                        }
                    }
                })
                .catch(function(){
                    btn.disabled = false;
                    btn.innerHTML = origHTML;
                });
            });
        })();
        </script>
        <?php
        return ob_get_clean();
    }


    /**
     * Enqueues shared CSS on classic editor (non-block) post screens.
     */
    public function enqueue_classic_editor_assets() {
        $screen = get_current_screen();
        if ( ! $screen || $screen->is_block_editor() || $screen->base !== 'post' ) {
            return;
        }
        wp_enqueue_style(
            'haayal-slug-shared',
            plugin_dir_url( dirname( __FILE__ ) ) . 'assets/css/ai-slug-shared.css',
            [],
            HAAYAL_AI_SLUG_TRANSLATOR_PLUGIN_VERSION
        );
    }

    /**
     * Enqueues the Gutenberg editor script for live slug translation.
     */
    public function enqueue_gutenberg_assets() {
        $screen = get_current_screen();
        if ( ! $screen || ! $screen->is_block_editor() ) {
            return;
        }

        $settings = Haayal_AI_Slug_Settings::get_settings();
        $post_type = $screen->post_type;

        // Only load for enabled post types.
        if ( ! in_array( $post_type, $settings['enabled_post_types'], true ) ) {
            return;
        }

        $post_id     = get_the_ID();
        $slug_source = $post_id ? get_post_meta( $post_id, '_slug_source', true ) : '';

        wp_enqueue_style(
            'haayal-slug-shared',
            plugin_dir_url( dirname( __FILE__ ) ) . 'assets/css/ai-slug-shared.css',
            [],
            HAAYAL_AI_SLUG_TRANSLATOR_PLUGIN_VERSION
        );

        wp_enqueue_script(
            'haayal-slug-gutenberg',
            plugin_dir_url( dirname( __FILE__ ) ) . 'assets/js/ai-slug-gutenberg.js',
            [ 'wp-data', 'wp-dom-ready', 'wp-api-fetch' ],
            HAAYAL_AI_SLUG_TRANSLATOR_PLUGIN_VERSION,
            true
        );

        $localize_data = [
            'slugSource' => $slug_source,
            'i18n'       => [
                'slugGeneratedByAi'  => __( 'Slug generated by AI', 'haayal-ai-slug-translator' ),
                'slugManuallyEdited' => __( 'Slug manually edited', 'haayal-ai-slug-translator' ),
                'regenerateSlug'     => __( 'Regenerate slug', 'haayal-ai-slug-translator' ),
                'translating'        => __( 'Translating…', 'haayal-ai-slug-translator' ),
                'alreadyBestOption'  => __( 'I tried, but this is already the best option', 'haayal-ai-slug-translator' ),
            ],
        ];

        if ( current_user_can( 'manage_options' ) ) {
            $localize_data['bulkUrl']  = admin_url( 'options-general.php?page=ai-slug-translator&tab=bulk' );
            $localize_data['i18n']['bulkTranslate'] = __( 'Bulk translate slugs', 'haayal-ai-slug-translator' );
        }

        wp_localize_script( 'haayal-slug-gutenberg', 'haayalGutenberg', $localize_data );
    }

    /**
     * Registers the REST API endpoint for slug translation.
     */
    public function register_translate_endpoint() {
        register_rest_route( 'haayal-ai-slug/v1', '/translate', [
            'methods'             => 'POST',
            'callback'            => [ $this, 'handle_translate_request' ],
            'permission_callback' => function () {
                return current_user_can( 'edit_posts' );
            },
        ] );
    }

    /**
     * Handles the REST API translation request from the Gutenberg editor.
     *
     * @param WP_REST_Request $request The REST request object.
     * @return WP_REST_Response The response with the translated slug.
     */
    public function handle_translate_request( $request ) {
        $title   = sanitize_text_field( $request->get_param( 'title' ) );
        $post_id = absint( $request->get_param( 'post_id' ) );

        if ( empty( $title ) ) {
            return new WP_REST_Response( [ 'error' => __( 'Title is empty.', 'haayal-ai-slug-translator' ) ], 400 );
        }

        $settings = Haayal_AI_Slug_Settings::get_settings();

        // Validate per-post capability and that the post type is enabled.
        if ( $post_id ) {
            if ( ! current_user_can( 'edit_post', $post_id ) ) {
                return new WP_REST_Response( [ 'error' => __( 'Permission denied.', 'haayal-ai-slug-translator' ) ], 403 );
            }
            $post = get_post( $post_id );
            if ( ! $post || ! in_array( $post->post_type, $settings['enabled_post_types'], true ) ) {
                return new WP_REST_Response( [ 'error' => __( 'Post type not enabled.', 'haayal-ai-slug-translator' ) ], 400 );
            }
        }

        $api_key = $settings['api_key'];

        Haayal_AI_Slug_Log::set_context( [ 'object_id' => $post_id, 'object_type' => 'post' ] );

        $slug = Haayal_AI_Slug_Helpers::translate_and_track( $title, $api_key, $settings['max_tokens'] ?? 20 );

        Haayal_AI_Slug_Log::set_context();

        if ( ! $slug ) {
            return new WP_REST_Response( [ 'error' => __( 'Translation failed or title is already in English.', 'haayal-ai-slug-translator' ) ], 422 );
        }

        // Store the generated slug in post meta if we have a valid post ID.
        if ( $post_id ) {
            update_post_meta( $post_id, '_generated_slug', $slug );
            update_post_meta( $post_id, '_slug_source', 'ai' );
        }

        return new WP_REST_Response( [ 'slug' => $slug ], 200 );
    }
}